/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UeberMichRouteImport } from './routes/ueber-mich'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as RabattcodesRouteImport } from './routes/rabattcodes'
import { Route as MethodenRouteImport } from './routes/methoden'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DiagnostikRouteImport } from './routes/diagnostik'
import { Route as AbrechnungRouteImport } from './routes/abrechnung'
import { Route as AblaufRouteImport } from './routes/ablauf'
import { Route as IndexRouteImport } from './routes/index'

const UeberMichRoute = UeberMichRouteImport.update({
  id: '/ueber-mich',
  path: '/ueber-mich',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const RabattcodesRoute = RabattcodesRouteImport.update({
  id: '/rabattcodes',
  path: '/rabattcodes',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodenRoute = MethodenRouteImport.update({
  id: '/methoden',
  path: '/methoden',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnostikRoute = DiagnostikRouteImport.update({
  id: '/diagnostik',
  path: '/diagnostik',
  getParentRoute: () => rootRouteImport,
} as any)
const AbrechnungRoute = AbrechnungRouteImport.update({
  id: '/abrechnung',
  path: '/abrechnung',
  getParentRoute: () => rootRouteImport,
} as any)
const AblaufRoute = AblaufRouteImport.update({
  id: '/ablauf',
  path: '/ablauf',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ablauf': typeof AblaufRoute
  '/abrechnung': typeof AbrechnungRoute
  '/diagnostik': typeof DiagnostikRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/methoden': typeof MethodenRoute
  '/rabattcodes': typeof RabattcodesRoute
  '/shop': typeof ShopRoute
  '/ueber-mich': typeof UeberMichRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ablauf': typeof AblaufRoute
  '/abrechnung': typeof AbrechnungRoute
  '/diagnostik': typeof DiagnostikRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/methoden': typeof MethodenRoute
  '/rabattcodes': typeof RabattcodesRoute
  '/shop': typeof ShopRoute
  '/ueber-mich': typeof UeberMichRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ablauf': typeof AblaufRoute
  '/abrechnung': typeof AbrechnungRoute
  '/diagnostik': typeof DiagnostikRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/methoden': typeof MethodenRoute
  '/rabattcodes': typeof RabattcodesRoute
  '/shop': typeof ShopRoute
  '/ueber-mich': typeof UeberMichRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ablauf'
    | '/abrechnung'
    | '/diagnostik'
    | '/impressum'
    | '/kontakt'
    | '/methoden'
    | '/rabattcodes'
    | '/shop'
    | '/ueber-mich'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ablauf'
    | '/abrechnung'
    | '/diagnostik'
    | '/impressum'
    | '/kontakt'
    | '/methoden'
    | '/rabattcodes'
    | '/shop'
    | '/ueber-mich'
  id:
    | '__root__'
    | '/'
    | '/ablauf'
    | '/abrechnung'
    | '/diagnostik'
    | '/impressum'
    | '/kontakt'
    | '/methoden'
    | '/rabattcodes'
    | '/shop'
    | '/ueber-mich'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AblaufRoute: typeof AblaufRoute
  AbrechnungRoute: typeof AbrechnungRoute
  DiagnostikRoute: typeof DiagnostikRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  MethodenRoute: typeof MethodenRoute
  RabattcodesRoute: typeof RabattcodesRoute
  ShopRoute: typeof ShopRoute
  UeberMichRoute: typeof UeberMichRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ueber-mich': {
      id: '/ueber-mich'
      path: '/ueber-mich'
      fullPath: '/ueber-mich'
      preLoaderRoute: typeof UeberMichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rabattcodes': {
      id: '/rabattcodes'
      path: '/rabattcodes'
      fullPath: '/rabattcodes'
      preLoaderRoute: typeof RabattcodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methoden': {
      id: '/methoden'
      path: '/methoden'
      fullPath: '/methoden'
      preLoaderRoute: typeof MethodenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostik': {
      id: '/diagnostik'
      path: '/diagnostik'
      fullPath: '/diagnostik'
      preLoaderRoute: typeof DiagnostikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abrechnung': {
      id: '/abrechnung'
      path: '/abrechnung'
      fullPath: '/abrechnung'
      preLoaderRoute: typeof AbrechnungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ablauf': {
      id: '/ablauf'
      path: '/ablauf'
      fullPath: '/ablauf'
      preLoaderRoute: typeof AblaufRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AblaufRoute: AblaufRoute,
  AbrechnungRoute: AbrechnungRoute,
  DiagnostikRoute: DiagnostikRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  MethodenRoute: MethodenRoute,
  RabattcodesRoute: RabattcodesRoute,
  ShopRoute: ShopRoute,
  UeberMichRoute: UeberMichRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
